# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gabrielbcsilva
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-api

package:
  individually: true
build:
  esbuild: false

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello-world
          method: get
  user:
    handler: handler.user
    events:
      - httpApi:
          path: /user
          method: get
  post:
    handler: handler.post
    events:
      - httpApi:
          path: /post
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  
